version: "3.3"
services:
  client:
    build: ./frontend
    container_name: client_side
    ports:
      - "3000:80"
  server:
    build: ./api
    container_name: server_side
    ports:
      - "5000:5000"